name: Build lua-debug
description: 'Build lua-debug'
inputs:
  deps_dir:
    description: 'Path to dependencies directory, where the build files for luamake and lua-debug will be stored.'
    default: 'deps'
  install_dir:
    description: 'Path to install directory, where the lua-debug files will be copied to.'
    default: 'install'
runs:
  using: "composite"
  steps:
    - uses: Silverlan/common_actions/action_start@main
      with:
        name: "pragma > build_luadebug"
  
    - name: Set Output Variables
      shell: bash
      id: set-output-vars
      run: |
        echo "deps-dir=deps" >> $GITHUB_OUTPUT
        echo "install-dir=install" >> $GITHUB_OUTPUT

    - name: Install Ninja
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build

    - name: Build luamake
      shell: bash
      run: |
        python build_luamake.py "{{ steps.set-output-vars.outputs.deps-dir }}"

    - name: Build luadebug
      if: runner.os == 'Linux'
      shell: bash
      run: |
        python build_luadebug.py "{{ steps.set-output-vars.outputs.deps-dir }}"

    # On Windows we have to run this in powershell
    - name: Build luadebug
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        python build_luadebug.py "{{ steps.set-output-vars.outputs.deps-dir }}"

    - name: Install
      shell: bash
      run: |
        python install_files.py "{{ steps.set-output-vars.outputs.deps-dir }}" "{{ steps.set-output-vars.outputs.install-dir }}"
  
    - uses: Silverlan/common_actions/action_end@main
