name: Build lua-debug (Powershell)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: "Windows x64 MSVC"
            artifact: "Windows-MSVC.tar.xz"
            build_type: "RelWithDebInfo"
            environment_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            cc: "cl"
            cxx: "cl"
            archiver: "7z a"
            generators: "Visual Studio 16 2022"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - name: Prep
        shell: bash
        run: |
          mkdir deps
          mkdir install

      - name: Build luamake
        shell: bash
        run: |
          python build_luamake.py "$(pwd)/deps"

      - name: Build luadebug
        shell: pwsh
        run: |
          python build_luadebug.py "$(pwd)/deps"

      - name: Install
        shell: bash
        run: |
          python install_files.py "$(pwd)/deps" "$(pwd)/install"
          
      - name: Print Files
        shell: bash
        run: |
          cd install
          ls -R
