name: Build lua-debug (Ubuntu)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
            name: "Ubuntu GCC-11"
            artifact: "ubuntu_gcc.7z"
            build_type: "RelWithDebInfo"
            cc: "clang-14"
            cxx: "clang++-14"
            archiver: "7z a"
            generators: "Unix Makefiles"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: false

      - name: Prep
        shell: bash
        run: |
          mkdir deps
          mkdir install

      - name: Build luamake
        shell: bash
        run: |
          python build_luamake.py "$(pwd)/deps"

      - name: Build luadebug
        shell: bash
        run: |
          python build_luadebug.py "$(pwd)/deps"

      - name: Install
        shell: bash
        run: |
          python install_files.py "$(pwd)/deps" "$(pwd)/install"
          
      - name: Print Files
        shell: bash
        run: |
          cd install
          ls -R
