name: Build Windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: "Windows x64 MSVC"
            artifact: "Windows-MSVC.tar.xz"
            build_type: "RelWithDebInfo"
            environment_script: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            cc: "cl"
            cxx: "cl"
            archiver: "7z a"
            generators: "Visual Studio 16 2022"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules : recursive
          repository: 'actboy168/lua-debug'
      - uses: actboy168/setup-luamake@master
      - if: matrix.platform == 'linux-arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - run: luamake lua compile/download_deps.lua
      - run: luamake -mode release -platform ${{ matrix.platform }}
      - run: npm install -g vsce ovsx
      - run: npx vsce publish --target ${{ matrix.platform }} -p ${{ secrets.VSCE_KEY }}
        working-directory: publish
        continue-on-error: true
      - run: npx ovsx publish --target ${{ matrix.platform }} -p ${{ secrets.OVSX_KEY }}
        working-directory: publish
        continue-on-error: true
      - if: matrix.platform == 'win32-x64'
        run: npx vsce publish --target win32-ia32 -p ${{ secrets.VSCE_KEY }}
        working-directory: publish
        continue-on-error: true
      - if: matrix.platform == 'win32-x64'
        run: npx ovsx publish --target win32-ia32 -p ${{ secrets.OVSX_KEY }}
        working-directory: publish
        continue-on-error: true

      - name: Copy Files
        shell: python
        run: |
          import shutil
          import os
          import platform

          if platform == "linux":
              luadebug_bin_path = "runtime/linux-x64/luajit"
              luadebug_bin_name = "luadebug.so"
          else:
              luadebug_bin_path = "runtime/win32-x64/luajit"
              luadebug_bin_name = "luadebug.dll"

          # Set luadebug_root = currentDirectory + "/lua-debug"
          luadebug_root = os.path.join(os.getcwd(), "lua-debug")

          # Set install_dir = currentDirectory + "/release"
          install_dir = os.path.join(os.getcwd(), "release")

          # Create path install_dir + "/lua/modules/lua-debug/" + luadebug_bin_path
          luadebug_module_path = os.path.join(install_dir, "lua", "modules", "lua-debug", luadebug_bin_path)
          os.makedirs(luadebug_module_path, exist_ok=True)

          # Copy contents of luadebug_root + "/publish/script" to install_dir + "/lua/modules/lua-debug/script/"
          script_source_dir = os.path.join(luadebug_root, "publish", "script")
          script_destination_dir = os.path.join(install_dir, "lua", "modules", "lua-debug", "script")
          shutil.copytree(script_source_dir, script_destination_dir)

          # Copy luadebug_root + "/publish/" + luadebug_bin_path + "/" + luadebug_bin_name to install_dir + "/lua/modules/lua-debug/" + luadebug_bin_path + "/"
          luadebug_bin_source = os.path.join(luadebug_root, "publish", luadebug_bin_path, luadebug_bin_name)
          luadebug_bin_destination = os.path.join(install_dir, "lua", "modules", "lua-debug", luadebug_bin_path, luadebug_bin_name)
          shutil.copy2(luadebug_bin_source, luadebug_bin_destination)

      - name: Release Binaries
        uses: Silverlan/common_actions/release_nightly_binaries@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}
